server:
  port: 8000

spring:
  application:
    name: sample-txle-dubbo-consumer
  datasource:
    url: jdbc:mysql://localhost:3306/txle?statementInterceptors=brave.mysql.TracingStatementInterceptor&useSSL=false
    username: root
    password: 123456
    driver-class-name: org.apache.servicecomb.saga.omega.jdbc.sqlinterceptor.wrapper.Driver
  zipkin:
    base-url: http://localhost:9411/api/v2/spans

alpha:
  cluster:
    address: localhost:8080

txle:
  prometheus:
    metrics:
      port: 9000
  transaction:
    pause-check-interval: 60
    auto-compensation:
      check-special-sql: false

dubbo:
  application:
    name: dubbo-consumer
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://localhost:2181
  provider:
    timeout: 10000
  consumer:
    timeout: 10000