server:
  port: 8003

spring:
  application:
    name: sample-txle-dubbo-provider-merchant
  datasource:
    platform: mysql
    schema: classpath:schema-mysql.sql
    data: classpath:data-mysql.sql
    url: jdbc:mysql://localhost:3306/db3?statementInterceptors=brave.mysql.TracingStatementInterceptor&useSSL=false
    username: root
    password: 123456
    driver-class-name: org.apache.servicecomb.saga.omega.jdbc.sqlinterceptor.wrapper.Driver
  zipkin:
    base-url: http://localhost:9411/api/v2/spans

alpha:
  cluster:
    address: localhost:8080

txle:
  prometheus:
    metrics:
      port: 9003
  transaction:
    pause-check-interval: 60
    auto-compensation:
      check-special-sql: false

dubbo:
  application:
    name: dubbo-provider-merchant
  protocol:
    name: dubbo
    port: 20883
  registry:
    address: zookeeper://localhost:2181
  provider:
    timeout: 10000
  consumer:
    timeout: 10000