server:
  port: 8000

eureka:
  client:
    serviceUrl:
      #http://localhost:8761/eureka/,http://localhost:8762/eureka/  逗号后不要有空格
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
  instance:
    prefer-ip-address: true
  healthcheck:
      enabled: true

spring:
  application:
    name: sample-txle-springcloud-global
  datasource:
    url: jdbc:mysql://localhost:3306/txle?statementInterceptors=brave.mysql.TracingStatementInterceptor&useSSL=false
    username: root
    password: 123456
    driver-class-name: org.apache.servicecomb.saga.omega.jdbc.sqlinterceptor.wrapper.Driver
  zipkin:
    base-url: http://localhost:9411/api/v2/spans

alpha:
  cluster:
    address: localhost:8080

txle:
  prometheus:
    metrics:
      port: 9000
  transaction:
    pause-check-interval: 60
    auto-compensation:
      check-special-sql: false

ribbon:
  ReadTimeout: 10000 # 每次到达ReadTimeout * 2 时，系统报超时错误
  ConnectTimeout: 10000
