server:
  port: 8000

spring:
  application:
    name: sample-txle-springboot-global
  datasource:
    url: jdbc:mysql://10.186.62.75:3308/txle?statementInterceptors=brave.mysql.TracingStatementInterceptor&useSSL=false
    username: root
    password: 123456
    driver-class-name: org.apache.servicecomb.saga.omega.jdbc.sqlinterceptor.wrapper.Driver
  zipkin:
    base-url: http://localhost:9411/api/v2/spans

alpha:
  cluster:
    address: localhost:8080
    httpaddress: localhost:8090
#    address: localhost:8080, localhost:8081

txle:
  prometheus:
    metrics:
      port: 9000
  transaction:
    pause-check-interval: 60
    auto-compensation:
      check-special-sql: false